parameters:
#    sdz_blog.example.class: Sdz\BlogBundle\Example
        mon_parametre: ma_valeur

services:
    sdz_blog.antispam:
        class: Sdz\BlogBundle\Antispam\SdzAntispam
        arguments: [@mailer, %locale%, 3] # Tableau d'arguments
